Repository ie3-institute/OSMoGrid, pull requests merged in 2021-11, with the labels that each got.

#78 Introduce gitflow
  AUTHORS
  Jenkinsfile
  README.md
  gradle/scripts/checkJavaVersion.gradle
  gradle/scripts/documentation.gradle
  gradle/scripts/jacoco.gradle
  gradle/scripts/pmd.gradle
  gradle/scripts/sonarqube.gradle
  gradle/scripts/spotbugs.gradle
  gradle/scripts/spotless.gradle
  gradle/scripts/tests.gradle
  gradle/scripts/vcs.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/de/osmogrid/config/OsmogridConfig.java
  src/main/java/de/osmogrid/controller/SessionController.java
  src/main/java/de/osmogrid/controller/graph/GraphController.java
  src/main/java/de/osmogrid/controller/graph/KMedoidsSameSize.java
  src/main/java/de/osmogrid/controller/grid/GridController.java
  src/main/java/de/osmogrid/controller/grid/LineBuilder.java
  src/main/java/de/osmogrid/interfaces/MissionControlOsmogrid.java
  src/main/java/de/osmogrid/interfaces/OsmogridMainControl.java
  src/main/java/de/osmogrid/main/MainController.java
  src/main/java/de/osmogrid/main/MissionControlOsmogridStandalone.java
  src/main/java/de/osmogrid/main/StartMissionControl.java
  src/main/java/de/osmogrid/model/SessionModel.java
  src/main/java/de/osmogrid/model/graph/DistanceWeightedOsmEdge.java
  src/main/java/de/osmogrid/model/graph/OsmGraph.java
  src/main/java/de/osmogrid/model/graph/OsmGridNode.java
  src/main/java/de/osmogrid/util/OsmDataProvider.java
  src/main/java/de/osmogrid/util/OsmReader.java
  src/main/java/de/osmogrid/util/OsmoGridUtils.java
  src/main/java/de/osmogrid/util/QuantityUtils.java
  src/main/java/de/osmogrid/util/enums/TargetFormat.java
  src/main/java/de/osmogrid/util/enums/TypeSourceFormat.java
  src/main/java/de/osmogrid/util/enums/VoltageLevel.java
  src/main/java/de/osmogrid/util/exceptions/EmptyClusterException.java
  src/main/java/de/osmogrid/util/exceptions/GridGenerationException.java
  src/main/java/de/osmogrid/util/exceptions/UnconnectedClusterException.java
  src/main/java/de/osmogrid/util/quantities/OsmoGridUnits.java
  src/main/java/de/osmogrid/util/quantities/PowerDensity.java
  src/test/groovy/graphController/GraphControllerTest.groovy
  src/test/java/utils/TestObjectFactory.java
Labels: enhancement, dependencies

#82 Add semantic versioning to main
  CHANGELOG.md
  build.gradle
  gradle/scripts/semVer.gradle
  version.properties
Labels: bug

#79 Scala 3 + akka typed Skeleton
  .github/dependabot.yml
  build.gradle
  gradle/scripts/tscfg.gradle
  src/main/resources/config/config-template.conf
  src/main/resources/config/config-template_old.conf
  src/main/scala/edu/ie3/osmogrid/cfg/OsmoGridConfig.scala
  src/main/scala/edu/ie3/osmogrid/guardian/OsmoGridGuardian.scala
  src/main/scala/edu/ie3/osmogrid/io/input/InputDataProvider.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultListener.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvGenerator.scala
  src/main/scala/edu/ie3/osmogrid/main/RunOsmoGridStandalone.scala
Labels: enhancement

#85 Fix tscfg-Version
  build.gradle
Labels: dependencies

#86 Document legacy code in activity diagrams
  .gitignore
  .readthedocs.yaml
  CHANGELOG.md
  README.md
  docs/legacy/uml/buildHighwayDistanceMatrix.puml
  docs/legacy/uml/buildRawStreetGraph.puml
  docs/legacy/uml/calculatePerpendicularMatrix.puml
  docs/legacy/uml/lvGeneration.puml
  docs/readthedocs/Makefile
  docs/readthedocs/_static/css/theme_override.css
  docs/readthedocs/conf.py
  docs/readthedocs/index.rst
  docs/readthedocs/legacy/legacy.md
  docs/readthedocs/make.bat
  docs/readthedocs/requirements.txt
Labels: documentation

#87 Protocol proposal
  docs/protocol/protocol.puml
  docs/readthedocs/concept.md
  docs/readthedocs/index.rst
  gradle/scripts/spotless.gradle
Labels: documentation, enhancement
