Repository ie3-institute/OSMoGrid, pull requests merged in 2022-05, with the labels that each got.

#138 Implementing `LvRegionCoordinator`, osm splitting
  .gitattributes
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/osmogrid/ActorStopSupport.scala
  src/main/scala/edu/ie3/osmogrid/ActorStopSupportStateless.scala
  src/main/scala/edu/ie3/osmogrid/cfg/ConfigFailFast.scala
  src/main/scala/edu/ie3/osmogrid/cfg/OsmoGridConfig.scala
  src/main/scala/edu/ie3/osmogrid/io/input/BoundaryAdminLevel.scala
  src/main/scala/edu/ie3/osmogrid/io/input/InputDataProvider.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/PbfGuardian.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/PbfWorker.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultListener.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvRegionCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/MunicipalityCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/coordinator/LvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/coordinator/coordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/BoundaryFactory.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/EntityAllocationStrategy.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/OsmoGridModelPartitioner.scala
  src/main/scala/edu/ie3/osmogrid/model/OsmoGridModel.scala
  src/test/resources/Corrupted_Osm.pbf
  src/test/resources/Empty_Osm.pbf
  src/test/resources/edu/ie3/osmogrid/lv/region_coordinator/DoBoCas.pbf
  src/test/resources/edu/ie3/osmogrid/lv/region_coordinator/DoBoCas_boundaries_level6.csv
  src/test/resources/edu/ie3/osmogrid/lv/region_coordinator/DoBoCas_boundaries_level8.csv
  src/test/resources/edu/ie3/osmogrid/lv/region_coordinator/DoBoCas_boundaries_level9.csv
  src/test/resources/edu/ie3/osmogrid/lv/region_coordinator/DoBoCas_overpass.txt
  src/test/resources/testConfig.conf
  src/test/scala/edu/ie3/osmogrid/cfg/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/osmogrid/io/input/InputDataProviderIT.scala
  src/test/scala/edu/ie3/osmogrid/lv/coordinator/LvCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/BoundaryFactorySpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinatorIT.scala
  src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinatorTestModel.scala
  src/test/scala/edu/ie3/test/common/UnitSpec.scala
Labels: enhancement

#183 Removing RocketChat from Jenkinsfile
  Jenkinsfile
Labels: ci

#190 Fix RelationMemberType
  src/main/scala/edu/ie3/osmogrid/model/Osm4ScalaMapper.scala
Labels: bug

#188 Updating reviewers in dependabot config
  .github/dependabot.yml
Labels: dependencies
