Repository ie3-institute/OSMoGrid, pull requests merged in 2022-03, with the labels that each got.

#153 Use svg files instead of png for readthedocs integration
  docs/readthedocs/_static/figures/puml/OsmoGridGuardian.png
  docs/readthedocs/_static/figures/puml/OsmoGridGuardian.svg
  docs/readthedocs/dev/concept.md
  gradle/scripts/documentation.gradle
Labels: documentation

#121 Lv Coordinator according to updated concept
  CHANGELOG.md
  docs/puml/actors/LvCoordinator.puml
  docs/readthedocs/_static/figures/puml/LvCoordinator.svg
  docs/readthedocs/dev/concept.md
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/osmogrid/ActorStopSupport.scala
  src/main/scala/edu/ie3/osmogrid/cfg/ConfigFailFast.scala
  src/main/scala/edu/ie3/osmogrid/cfg/OsmoGridConfig.scala
  src/main/scala/edu/ie3/osmogrid/exception/RequestFailedException.scala
  src/main/scala/edu/ie3/osmogrid/guardian/OsmoGridGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/StopSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/run.scala
  src/main/scala/edu/ie3/osmogrid/io/input/InputDataProvider.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultListener.scala
  src/main/scala/edu/ie3/osmogrid/lv/DistrictCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvGridGenerator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvRegionCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/MunicipalityCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/SubDistrictCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/coordinator/LvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/coordinator/coordinator.scala
  src/main/scala/edu/ie3/osmogrid/model/OsmoGridModel.scala
  src/main/scala/edu/ie3/osmogrid/model/PbfFilter.scala
  src/test/scala/edu/ie3/osmogrid/cfg/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/RunGuardianSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/SubGridHandlingSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/coordinator/LvCoordinatorSpec.scala
Labels: enhancement

#158 Update gradle to 7.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies
