Repository ie3-institute/OSMoGrid, pull requests merged in 2023-11, with the labels that each got.

#342 Standardizing actor messages.
  src/main/scala/edu/ie3/osmogrid/cfg/ConfigFailFast.scala
  src/main/scala/edu/ie3/osmogrid/guardian/OsmoGridGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/guardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/StopSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/SubGridHandling.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/run.scala
  src/main/scala/edu/ie3/osmogrid/io/input/InputDataProvider.scala
  src/main/scala/edu/ie3/osmogrid/io/input/OsmSource.scala
  src/main/scala/edu/ie3/osmogrid/io/input/input.scala
  src/main/scala/edu/ie3/osmogrid/io/input/package.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/PbfGuardian.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/PbfWorker.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/pbf.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultCsvSink.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultListener.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultListenerProtocol.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultSink.scala
  src/main/scala/edu/ie3/osmogrid/io/output/output.scala
  src/main/scala/edu/ie3/osmogrid/lv/DistrictCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvGridGenerator.scala
  src/main/scala/edu/ie3/osmogrid/lv/MunicipalityCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/SubDistrictCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/lv.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/region_coordinator.scala
  src/main/scala/edu/ie3/osmogrid/main/RunOsmoGridStandalone.scala
  src/main/scala/edu/ie3/osmogrid/messages/Mv.scala
  src/main/scala/edu/ie3/osmogrid/mv/VoronoiCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/mv/mv.scala
  src/test/scala/edu/ie3/osmogrid/guardian/OsmoGridGuardianSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/RunGuardianSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/SubGridHandlingSpec.scala
  src/test/scala/edu/ie3/osmogrid/io/input/InputDataProviderIT.scala
  src/test/scala/edu/ie3/osmogrid/io/output/ResultCsvSinkIT.scala
  src/test/scala/edu/ie3/osmogrid/io/output/ResultListenerIT.scala
  src/test/scala/edu/ie3/osmogrid/lv/LvCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/LvGridGeneratorSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinatorIT.scala
  src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvTestModel.scala
  src/test/scala/edu/ie3/osmogrid/mv/VoronoiCoordinatorSpec.scala
Labels: refactoring

#341 Adding mv coordinator
  InputData/fuerweiler.conf
  docs/readthedocs/use/config.md
  gradle/scripts/spotless.gradle
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/osmogrid/cfg/ConfigFailFast.scala
  src/main/scala/edu/ie3/osmogrid/cfg/OsmoGridConfig.scala
  src/main/scala/edu/ie3/osmogrid/graph/OsmGraph.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/StopSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/SubGridHandling.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/VoltageSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/run.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvGraphGeneratorSupport.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvGridGenerator.scala
  src/main/scala/edu/ie3/osmogrid/lv/lv.scala
  src/main/scala/edu/ie3/osmogrid/model/OsmoGridModel.scala
  src/main/scala/edu/ie3/osmogrid/mv/MvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/mv/mv.scala
  src/main/scala/utils/GraphUtils.scala
  src/main/scala/utils/GridContainerUtils.scala
  src/main/scala/utils/GridConversion.scala
  src/main/scala/utils/OsmoGridUtils.scala
  src/main/scala/utils/VoltageUtils.scala
  src/test/resources/test_config.conf
  src/test/scala/edu/ie3/osmogrid/cfg/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/RunGuardianSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/SubGridHandlingSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/LvCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/LvGraphGeneratorSupportSpec.scala
  src/test/scala/edu/ie3/osmogrid/mv/MvCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/mv/VoronoiCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/utils/GridContainerUtilsSpec.scala
  src/test/scala/edu/ie3/osmogrid/utils/GridConversionSpec.scala
  src/test/scala/edu/ie3/osmogrid/utils/OsmoGridUtilsSpec.scala
  src/test/scala/edu/ie3/osmogrid/utils/VoltageUtilsSpec.scala
  src/test/scala/edu/ie3/test/common/GridSupport.scala
  src/test/scala/edu/ie3/test/common/MvTestData.scala
  src/test/scala/edu/ie3/test/common/OsmTestData.scala
Labels: enhancement

#346 Replace akka with pekko
  CHANGELOG.md
  build.gradle
  src/main/scala/edu/ie3/osmogrid/ActorStopSupport.scala
  src/main/scala/edu/ie3/osmogrid/ActorStopSupportStateless.scala
  src/main/scala/edu/ie3/osmogrid/cfg/ConfigFailFast.scala
  src/main/scala/edu/ie3/osmogrid/guardian/OsmoGridGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/guardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/StopSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/SubGridHandling.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/run.scala
  src/main/scala/edu/ie3/osmogrid/io/input/InputDataProvider.scala
  src/main/scala/edu/ie3/osmogrid/io/input/OsmSource.scala
  src/main/scala/edu/ie3/osmogrid/io/input/input.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/PbfGuardian.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/PbfWorker.scala
  src/main/scala/edu/ie3/osmogrid/io/input/pbf/pbf.scala
  src/main/scala/edu/ie3/osmogrid/io/output/ResultListener.scala
  src/main/scala/edu/ie3/osmogrid/io/output/output.scala
  src/main/scala/edu/ie3/osmogrid/lv/DistrictCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvGridGenerator.scala
  src/main/scala/edu/ie3/osmogrid/lv/MunicipalityCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/SubDistrictCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/lv.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/lv/region_coordinator/region_coordinator.scala
  src/main/scala/edu/ie3/osmogrid/main/RunOsmoGridStandalone.scala
  src/main/scala/edu/ie3/osmogrid/mv/MvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/mv/VoronoiCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/mv/mv.scala
  src/main/scala/utils/VoronoiUtils.scala
  src/test/resources/logback-test.xml
  src/test/scala/edu/ie3/osmogrid/guardian/OsmoGridGuardianSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/RunGuardianSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/SubGridHandlingSpec.scala
  src/test/scala/edu/ie3/osmogrid/io/input/AssetSourceSpec.scala
  src/test/scala/edu/ie3/osmogrid/io/input/InputDataProviderIT.scala
  src/test/scala/edu/ie3/osmogrid/io/input/OsmSourceIT.scala
  src/test/scala/edu/ie3/osmogrid/io/output/ResultListenerIT.scala
  src/test/scala/edu/ie3/osmogrid/lv/LvCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/LvGridGeneratorSpec.scala
  src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinatorIT.scala
  src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvTestModel.scala
  src/test/scala/edu/ie3/osmogrid/mv/MvCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/mv/VoronoiCoordinatorSpec.scala
  src/test/scala/edu/ie3/test/common/UnitSpec.scala
Labels: dependencies

#347 Fix dev pipeline
  Jenkinsfile
Labels: bug
