Repository ie3-institute/OSMoGrid, pull requests merged in 2024-05, with the labels that each got.

#418 Change transformer input parameter to psdm requirements
  CHANGELOG.md
  input/fuerweiler/assets/transformer_2_w_type_input.csv
Labels: invalid

#407 Adapting run initialization.
  CHANGELOG.md
  input/fuerweiler/fuerweiler.conf
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/osmogrid/cfg/ConfigFailFast.scala
  src/main/scala/edu/ie3/osmogrid/cfg/OsmoGridConfig.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/RunSupport.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/SubGridHandling.scala
  src/main/scala/edu/ie3/osmogrid/guardian/run/run.scala
  src/main/scala/edu/ie3/osmogrid/mv/MvCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/mv/MvGraphGeneratorSupport.scala
  src/main/scala/edu/ie3/osmogrid/mv/VoronoiCoordinator.scala
  src/main/scala/edu/ie3/osmogrid/mv/VoronoiPolygonSupport.scala
  src/main/scala/edu/ie3/osmogrid/mv/mv.scala
  src/test/resources/test_config.conf
  src/test/scala/edu/ie3/osmogrid/cfg/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/RunGuardianSpec.scala
  src/test/scala/edu/ie3/osmogrid/guardian/run/SubGridHandlingSpec.scala
  src/test/scala/edu/ie3/osmogrid/io/output/ResultListenerIT.scala
  src/test/scala/edu/ie3/osmogrid/mv/MvCoordinatorSpec.scala
  src/test/scala/edu/ie3/osmogrid/mv/MvGraphGeneratorSupportSpec.scala
  src/test/scala/edu/ie3/osmogrid/mv/VoronoiPolygonSupportSpec.scala
  src/test/scala/edu/ie3/test/common/MvTestData.scala
Labels: enhancement, refactoring

#429 Preventing unconnected nodes or subgrids.
  CHANGELOG.md
  input/fuerweiler/fuerweiler.conf
  src/main/scala/edu/ie3/osmogrid/exception/ClusterException.scala
  src/main/scala/edu/ie3/osmogrid/graph/OsmGraph.scala
  src/main/scala/edu/ie3/osmogrid/lv/LvGridGeneratorSupport.scala
  src/main/scala/edu/ie3/osmogrid/main/RunOsmoGridStandalone.scala
  src/main/scala/utils/Clustering.scala
  src/main/scala/utils/Connections.scala
  src/test/scala/edu/ie3/osmogrid/utils/ClusteringSpec.scala
Labels: bug

#432 Refactor getAllUniqueCombinations avoid nested loops
  CHANGELOG.md
  src/main/scala/utils/Connections.scala
  src/main/scala/utils/OsmoGridUtils.scala
Labels: bug, enhancement
